# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SayingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='-')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.AddField(
            model_name='sayingpost',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduce.Subject'),
        ),
    ]
